# Generated by Django 6.0.5 on 2026-06-01 23:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Lucide icon name (e.g. 'LayoutDashboard', 'DollarSign')",
                        max_length=50,
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Route path (e.g. '/app/financial/gl')",
                        max_length=200,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "permission_codename",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Required permission codename (e.g. 'view_journalentry')",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "level",
                    models.PositiveIntegerField(
                        default=0, help_text="Nesting level: 0=root, 1=sub, 2=sub-sub"
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Module grouping tag (e.g. 'financial', 'scm')",
                        max_length=50,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core.menu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "Menus",
                "db_table": "core_menu",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MenuRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_roles",
                        to="core.menu",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_roles",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu Role",
                "verbose_name_plural": "Menu Roles",
                "db_table": "core_menu_role",
                "unique_together": {("menu", "role")},
            },
        ),
    ]
