# Generated by Django 6.0.5 on 2026-06-02 00:57

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("page_key", models.SlugField(max_length=100, unique=True)),
                ("page_title", models.CharField(max_length=200)),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("form", "Form"),
                            ("list", "List"),
                            ("detail", "Detail"),
                            ("dashboard", "Dashboard"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        help_text="Module grouping (financial, scm, crm, mrp, hrm, admin)",
                        max_length=50,
                    ),
                ),
                (
                    "entity_model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Django model name",
                        max_length=100,
                    ),
                ),
                (
                    "api_endpoint",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("single", "Single Column"),
                            ("two_column", "Two Column"),
                            ("tabs", "Tabs"),
                            ("wizard", "Wizard"),
                        ],
                        default="single",
                        max_length=20,
                    ),
                ),
                (
                    "desktop_layout",
                    models.CharField(
                        choices=[
                            ("single", "Single Column"),
                            ("two_column", "Two Column"),
                            ("tabs", "Tabs"),
                            ("wizard", "Wizard"),
                        ],
                        default="single",
                        max_length=20,
                    ),
                ),
                (
                    "mobile_layout",
                    models.CharField(
                        choices=[
                            ("single", "Single Column"),
                            ("two_column", "Two Column"),
                            ("tabs", "Tabs"),
                            ("wizard", "Wizard"),
                        ],
                        default="single",
                        max_length=20,
                    ),
                ),
                (
                    "list_mobile_view",
                    models.CharField(
                        choices=[("table", "Table"), ("card", "Card")],
                        default="card",
                        max_length=10,
                    ),
                ),
                (
                    "mobile_group_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Field name for card grouping",
                        max_length=100,
                    ),
                ),
                ("actions", models.JSONField(blank=True, default=list)),
                ("breadcrumbs", models.JSONField(blank=True, default=list)),
                ("page_size", models.PositiveIntegerField(default=25)),
                (
                    "sort_default",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "sort_direction",
                    models.CharField(
                        choices=[("asc", "Ascending"), ("desc", "Descending")],
                        default="asc",
                        max_length=4,
                    ),
                ),
            ],
            options={
                "verbose_name": "Page Config",
                "verbose_name_plural": "Page Configs",
                "db_table": "core_page_config",
                "ordering": ["module", "page_key"],
            },
        ),
        migrations.AlterField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="menu",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="menurole",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="usercompany",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.CreateModel(
            name="PageConfigField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("field_name", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=200)),
                (
                    "placeholder",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("help_text", models.CharField(blank=True, default="", max_length=500)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("textarea", "Textarea"),
                            ("number", "Number"),
                            ("decimal", "Decimal"),
                            ("email", "Email"),
                            ("password", "Password"),
                            ("date", "Date"),
                            ("datetime", "DateTime"),
                            ("time", "Time"),
                            ("select", "Select"),
                            ("multi_select", "Multi Select"),
                            ("checkbox", "Checkbox"),
                            ("radio", "Radio"),
                            ("file", "File"),
                            ("image", "Image"),
                            ("hidden", "Hidden"),
                            ("heading", "Heading"),
                            ("divider", "Divider"),
                            ("json", "JSON"),
                            ("parent_child", "Parent-Child Table"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="String, Integer, etc.",
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("readonly", models.BooleanField(default=False)),
                ("hidden", models.BooleanField(default=False)),
                ("disabled", models.BooleanField(default=False)),
                (
                    "default_value",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "group_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="header, details, totals, notes",
                        max_length=50,
                    ),
                ),
                (
                    "col_span",
                    models.PositiveIntegerField(
                        default=1, help_text="1-12 column span"
                    ),
                ),
                (
                    "width",
                    models.CharField(
                        choices=[
                            ("full", "Full"),
                            ("half", "Half"),
                            ("third", "Third"),
                            ("quarter", "Quarter"),
                        ],
                        default="full",
                        max_length=10,
                    ),
                ),
                ("show_on_desktop", models.BooleanField(default=True)),
                ("show_on_mobile", models.BooleanField(default=True)),
                ("desktop_col_span", models.PositiveIntegerField(default=1)),
                ("mobile_col_span", models.PositiveIntegerField(default=12)),
                (
                    "mobile_render_as",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("badge", "Badge"),
                            ("card", "Card"),
                            ("compact", "Compact"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("min_length", models.PositiveIntegerField(blank=True, null=True)),
                ("max_length", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                ("pattern", models.CharField(blank=True, default="", max_length=200)),
                (
                    "custom_validator",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "options_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("static", "Static"),
                            ("api", "API"),
                            ("enum", "Enum"),
                            ("model", "Model"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("options", models.JSONField(blank=True, default=list)),
                (
                    "options_api",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "options_label_field",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "options_value_field",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "option_group_by",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "related_entity",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "related_display",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("related_search", models.JSONField(blank=True, default=dict)),
                ("related_fields", models.JSONField(blank=True, default=list)),
                ("show_when", models.JSONField(blank=True, default=dict)),
                ("depends_on", models.JSONField(blank=True, default=dict)),
                ("is_column", models.BooleanField(default=False)),
                ("column_order", models.PositiveIntegerField(default=0)),
                (
                    "column_width",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "column_align",
                    models.CharField(
                        choices=[
                            ("left", "Left"),
                            ("center", "Center"),
                            ("right", "Right"),
                        ],
                        default="left",
                        max_length=10,
                    ),
                ),
                ("sortable", models.BooleanField(default=False)),
                ("filterable", models.BooleanField(default=False)),
                ("searchable", models.BooleanField(default=False)),
                ("aggregate", models.CharField(blank=True, default="", max_length=20)),
                ("render_as", models.CharField(blank=True, default="", max_length=20)),
                (
                    "line_entity",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("line_fields", models.JSONField(blank=True, default=list)),
                (
                    "permission_read",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "permission_write",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("icon", models.CharField(blank=True, default="", max_length=50)),
                ("prefix", models.CharField(blank=True, default="", max_length=20)),
                ("suffix", models.CharField(blank=True, default="", max_length=20)),
                ("format", models.CharField(blank=True, default="", max_length=50)),
                ("badge_color", models.JSONField(blank=True, default=dict)),
                ("css_class", models.CharField(blank=True, default="", max_length=200)),
                (
                    "page_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="core.pageconfig",
                    ),
                ),
                (
                    "parent_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_fields",
                        to="core.pageconfigfield",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page Config Field",
                "verbose_name_plural": "Page Config Fields",
                "db_table": "core_page_config_field",
                "ordering": ["sort_order", "field_name"],
            },
        ),
    ]
