# Generated by Django 6.0.5 on 2026-06-02 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_pageconfig_alter_company_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="company",
            name="base_currency",
            field=models.CharField(blank=True, default="MYR", max_length=3),
        ),
        migrations.AddField(
            model_name="company",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="country",
            field=models.CharField(blank=True, default="MY", max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="date_format",
            field=models.CharField(blank=True, default="Y-m-d", max_length=20),
        ),
        migrations.AddField(
            model_name="company",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="company",
            name="fiscal_year_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="fiscal_year_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="is_group",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(blank=True, upload_to="company_logos/"),
        ),
        migrations.AddField(
            model_name="company",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="core.company",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="company",
            name="postcode",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="company",
            name="state",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="timezone",
            field=models.CharField(
                blank=True, default="Asia/Kuala_Lumpur", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="usercompany",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
