# Generated by Django 6.0.5 on 2026-06-02 14:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_loginhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSetting",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("smtp_host", models.CharField(blank=True, default="", max_length=255)),
                ("smtp_port", models.PositiveIntegerField(default=587)),
                (
                    "smtp_username",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "smtp_password",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("smtp_use_tls", models.BooleanField(default=True)),
                ("smtp_use_ssl", models.BooleanField(default=False)),
                (
                    "from_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("from_name", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "verbose_name": "Email Setting",
                "verbose_name_plural": "Email Settings",
                "db_table": "core_email_setting",
            },
        ),
    ]
