# Generated by Django 6.0.5 on 2026-06-02 23:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0005_loginhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowDefinition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("financial", "Financial"),
                            ("scm", "Supply Chain"),
                            ("crm", "CRM"),
                            ("mrp", "MRP"),
                            ("hrm", "HRM"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        help_text="e.g. PurchaseOrder, SalesInvoice, LeaveRequest",
                        max_length=100,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "flow_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="React-flow nodes/edges JSON",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_global_template", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = global template",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_definitions",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Definition",
                "verbose_name_plural": "Workflow Definitions",
                "db_table": "core_workflow_definition",
                "ordering": ["module", "document_type", "name"],
                "unique_together": {("name", "company", "version")},
            },
        ),
        migrations.CreateModel(
            name="WorkflowEdge",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("source_node_id", models.CharField(max_length=100)),
                ("target_node_id", models.CharField(max_length=100)),
                ("label", models.CharField(blank=True, default="", max_length=200)),
                ("condition", models.JSONField(blank=True, default=dict)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edges",
                        to="core.workflowdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Edge",
                "verbose_name_plural": "Workflow Edges",
                "db_table": "core_workflow_edge",
                "ordering": ["workflow", "source_node_id", "target_node_id"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("document_type", models.CharField(max_length=100)),
                ("document_id", models.UUIDField()),
                (
                    "current_node_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_executions",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created the document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_created_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        help_text="User who submitted for approval",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="core.workflowdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Execution",
                "verbose_name_plural": "Workflow Executions",
                "db_table": "core_workflow_execution",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowNode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "node_id",
                    models.CharField(
                        help_text="React-flow node ID (e.g. 'node_1')", max_length=100
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("start", "Start"),
                            ("end", "End"),
                            ("approve", "Approve"),
                            ("condition", "Condition"),
                            ("notify", "Notify"),
                            ("action", "Action"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=200)),
                ("position_x", models.FloatField(default=0)),
                ("position_y", models.FloatField(default=0)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="core.workflowdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Node",
                "verbose_name_plural": "Workflow Nodes",
                "db_table": "core_workflow_node",
                "ordering": ["workflow", "node_id"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowExecutionStep",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("return", "Return"),
                            ("delegate", "Delegate"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "approver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_steps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delegated_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delegated_approval_steps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="core.workflowexecution",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="execution_steps",
                        to="core.workflownode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Execution Step",
                "verbose_name_plural": "Workflow Execution Steps",
                "db_table": "core_workflow_execution_step",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("object_id", models.UUIDField(db_index=True)),
                ("file", models.FileField(upload_to="attachments/%Y/%m/")),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField()),
                ("mime_type", models.CharField(blank=True, default="", max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
                "db_table": "core_attachment",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="core_attach_content_d3cac2_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["document_type", "document_id"],
                name="core_workfl_documen_449ba4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(fields=["status"], name="core_workfl_status_49826b_idx"),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["company", "status"], name="core_workfl_company_3b2885_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workflownode",
            unique_together={("workflow", "node_id")},
        ),
    ]
