# Generated by Django 6.0.5 on 2026-06-03 01:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_merge_0006_branches"),
    ]

    operations = [
        migrations.CreateModel(
            name="NumberingSeries",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "document_type",
                    models.CharField(
                        help_text="e.g., invoice, purchase_order, quotation",
                        max_length=100,
                    ),
                ),
                ("prefix", models.CharField(blank=True, default="", max_length=20)),
                (
                    "date_format",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g., YYYYMM, YYMM, or blank",
                        max_length=20,
                    ),
                ),
                ("next_number", models.PositiveIntegerField(default=1)),
                (
                    "reset_period",
                    models.CharField(
                        choices=[
                            ("yearly", "Yearly"),
                            ("monthly", "Monthly"),
                            ("never", "Never"),
                        ],
                        default="yearly",
                        max_length=20,
                    ),
                ),
                (
                    "padding",
                    models.PositiveIntegerField(
                        default=6, help_text="Zero-padding for running number"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="numbering_series",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Numbering Series",
                "verbose_name_plural": "Numbering Series",
                "db_table": "core_numbering_series",
                "ordering": ["document_type"],
                "indexes": [
                    models.Index(
                        fields=["company"], name="core_number_company_841033_idx"
                    ),
                    models.Index(
                        fields=["document_type"], name="core_number_documen_4b9312_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document_type", "company"),
                        name="uq_numbering_series_doc_type_company",
                    )
                ],
            },
        ),
    ]
