# Generated by Django 6.0.5 on 2026-06-03 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_numberingseries"),
    ]

    operations = [
        migrations.AddField(
            model_name="numberingseries",
            name="last_reset_at",
            field=models.DateTimeField(
                blank=True, help_text="When the counter was last reset", null=True
            ),
        ),
    ]
