# Generated by Django 6.0.5 on 2026-06-03 06:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="NumberingSeriesPolicy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "document_type",
                    models.CharField(
                        help_text="e.g., invoice, purchase_order",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("prefix", models.CharField(blank=True, default="", max_length=20)),
                (
                    "date_format",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g., YYYYMM, YYMM",
                        max_length=20,
                    ),
                ),
                (
                    "padding",
                    models.PositiveIntegerField(
                        default=6, help_text="Zero-padding for running number"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Numbering Series Policy",
                "verbose_name_plural": "Numbering Series Policies",
                "db_table": "core_numbering_policy",
                "ordering": ["document_type"],
            },
        ),
        migrations.CreateModel(
            name="CompanyNumberingSeries",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("next_number", models.PositiveIntegerField(default=1)),
                (
                    "reset_period",
                    models.CharField(
                        choices=[
                            ("yearly", "Yearly"),
                            ("monthly", "Monthly"),
                            ("never", "Never"),
                        ],
                        default="yearly",
                        max_length=20,
                    ),
                ),
                (
                    "last_reset_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the counter was last reset",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="numbering_assignments",
                        to="core.company",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_assignments",
                        to="core.numberingseriespolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Numbering Series",
                "verbose_name_plural": "Company Numbering Series",
                "db_table": "core_company_numbering_series",
                "ordering": ["policy__document_type"],
                "indexes": [
                    models.Index(
                        fields=["company"], name="core_compan_company_bd0ac6_idx"
                    ),
                    models.Index(
                        fields=["policy"], name="core_compan_policy__b95a8b_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("policy", "company"),
                        name="uq_company_numbering_policy_company",
                    )
                ],
            },
        ),
    ]
