# Generated by Django 6.0.5 on 2026-06-03 07:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_migrate_numbering_data"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="numberingseries",
            name="core_number_company_841033_idx",
        ),
        migrations.RemoveIndex(
            model_name="numberingseries",
            name="core_number_documen_4b9312_idx",
        ),
        migrations.RemoveConstraint(
            model_name="numberingseries",
            name="uq_numbering_series_doc_type_company",
        ),
        migrations.DeleteModel(
            name="NumberingSeries",
        ),
    ]
