# Generated by Django 6.0.5 on 2026-06-04 03:13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_channel_message_messageattachment_channelmember_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalPolicy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=200)),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("financial", "Financial"),
                            ("scm", "Supply Chain"),
                            ("crm", "CRM"),
                            ("mrp", "MRP"),
                            ("hrm", "HRM"),
                        ],
                        max_length=50,
                    ),
                ),
                ("document_type", models.CharField(max_length=100)),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of condition objects: [{field, operator, value, value_to?}]",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100, help_text="Lower number = higher priority"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = global policy",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_policies",
                        to="core.company",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="core.workflowdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Policy",
                "verbose_name_plural": "Approval Policies",
                "db_table": "core_approval_policy",
                "ordering": ["module", "document_type", "priority", "name"],
            },
        ),
    ]
