# Generated by Django 6.0.5 on 2026-06-04 04:12

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_approvalpolicy"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=200)),
                (
                    "entity_type",
                    models.SlugField(help_text="Unique key e.g. 'items'", unique=True),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "column_definitions",
                    models.JSONField(
                        default=list,
                        help_text="List of column dicts: [{name, label, type, required, max_length, fk_model, format_example}]",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Import Template",
                "verbose_name_plural": "Import Templates",
                "db_table": "core_import_template",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("file_name", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("validating", "Validating"),
                            ("importing", "Importing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.IntegerField(default=0)),
                ("success_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("warning_count", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "error_log",
                    models.TextField(
                        blank=True, help_text="General job-level error messages"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_jobs",
                        to="core.company",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="core.importtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import Job",
                "verbose_name_plural": "Import Jobs",
                "db_table": "core_import_job",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportHistory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("entity_type", models.SlugField()),
                (
                    "action",
                    models.CharField(
                        choices=[("import", "Import"), ("rollback", "Rollback")],
                        max_length=20,
                    ),
                ),
                ("record_count", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_entries",
                        to="core.importjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import History",
                "verbose_name_plural": "Import Histories",
                "db_table": "core_import_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportRow",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("row_number", models.IntegerField()),
                (
                    "raw_data",
                    models.JSONField(default=dict, help_text="Original CSV row data"),
                ),
                (
                    "mapped_data",
                    models.JSONField(default=dict, help_text="Post-mapping data"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("valid", "Valid"),
                            ("error", "Error"),
                            ("imported", "Imported"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("errors", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("imported_record_id", models.UUIDField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="core.importjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import Row",
                "verbose_name_plural": "Import Rows",
                "db_table": "core_import_row",
                "ordering": ["job", "row_number"],
                "unique_together": {("job", "row_number")},
            },
        ),
    ]
