# Generated by Django 6.0.5 on 2026-06-04 05:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_importtemplate_importjob_importhistory_importrow"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpeningBalanceMigration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("go_live_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_migrations",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opening_migrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Opening Balance Migration",
                "verbose_name_plural": "Opening Balance Migrations",
                "db_table": "core_opening_balance_migration",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OpeningBalanceInventory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("item_code", models.CharField(max_length=50)),
                ("warehouse_code", models.CharField(max_length=50)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=18)),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=18)),
                ("row_number", models.IntegerField(default=0)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("errors", models.JSONField(blank=True, default=list)),
                (
                    "migration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_lines",
                        to="core.openingbalancemigration",
                    ),
                ),
            ],
            options={
                "db_table": "core_opening_balance_inventory",
                "ordering": ["row_number"],
            },
        ),
        migrations.CreateModel(
            name="OpeningBalanceGL",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("account_code", models.CharField(max_length=50)),
                ("account_name", models.CharField(blank=True, max_length=200)),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("row_number", models.IntegerField(default=0)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("errors", models.JSONField(blank=True, default=list)),
                (
                    "migration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gl_lines",
                        to="core.openingbalancemigration",
                    ),
                ),
            ],
            options={
                "db_table": "core_opening_balance_gl",
                "ordering": ["row_number"],
            },
        ),
        migrations.CreateModel(
            name="OpeningBalanceAsset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("asset_code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("purchase_date", models.DateField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "accumulated_depreciation",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "useful_life",
                    models.IntegerField(blank=True, help_text="Years", null=True),
                ),
                ("row_number", models.IntegerField(default=0)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("errors", models.JSONField(blank=True, default=list)),
                (
                    "migration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_lines",
                        to="core.openingbalancemigration",
                    ),
                ),
            ],
            options={
                "db_table": "core_opening_balance_asset",
                "ordering": ["row_number"],
            },
        ),
        migrations.CreateModel(
            name="OpeningBalanceAR",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("customer_code", models.CharField(max_length=50)),
                ("invoice_no", models.CharField(max_length=100)),
                ("invoice_date", models.DateField()),
                ("due_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(default="MYR", max_length=3)),
                ("row_number", models.IntegerField(default=0)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("errors", models.JSONField(blank=True, default=list)),
                (
                    "migration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ar_lines",
                        to="core.openingbalancemigration",
                    ),
                ),
            ],
            options={
                "db_table": "core_opening_balance_ar",
                "ordering": ["row_number"],
            },
        ),
        migrations.CreateModel(
            name="OpeningBalanceAP",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("supplier_code", models.CharField(max_length=50)),
                ("invoice_no", models.CharField(max_length=100)),
                ("invoice_date", models.DateField()),
                ("due_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency", models.CharField(default="MYR", max_length=3)),
                ("row_number", models.IntegerField(default=0)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("errors", models.JSONField(blank=True, default=list)),
                (
                    "migration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ap_lines",
                        to="core.openingbalancemigration",
                    ),
                ),
            ],
            options={
                "db_table": "core_opening_balance_ap",
                "ordering": ["row_number"],
            },
        ),
    ]
