# Generated by Django 6.0.5 on 2026-06-04 07:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_openingbalancemigration_openingbalanceinventory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustryTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("version", models.CharField(default="1.0.0", max_length=20)),
                ("module_dependencies", models.JSONField(blank=True, default=list)),
                ("menu_config", models.JSONField(blank=True, default=list)),
                ("page_config", models.JSONField(blank=True, default=list)),
                ("workflow_config", models.JSONField(blank=True, default=list)),
                ("gl_account_config", models.JSONField(blank=True, default=list)),
                ("report_config", models.JSONField(blank=True, default=list)),
                ("seed_data", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "core_industry_template",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IndustryTemplateInstallation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("uninstalled", "Uninstalled")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("configuration_overrides", models.JSONField(blank=True, default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_installations",
                        to="core.company",
                    ),
                ),
                (
                    "installed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="template_installations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installations",
                        to="core.industrytemplate",
                    ),
                ),
            ],
            options={
                "db_table": "core_industry_template_installation",
                "ordering": ["-installed_at"],
                "unique_together": {("template", "company", "status")},
            },
        ),
    ]
