# Generated by Django 6.0.5 on 2026-06-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_industrytemplate_industrytemplateinstallation"),
    ]

    operations = [
        migrations.AddField(
            model_name="industrytemplate",
            name="template_version",
            field=models.CharField(default="1.0.0", max_length=20),
        ),
        migrations.AlterField(
            model_name="industrytemplate",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
