# Generated by Django 6.0.5 on 2026-06-04 08:17

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_industrytemplate_template_version_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionMigration",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("go_live_date", models.DateField()),
                (
                    "migration_option",
                    models.CharField(
                        choices=[("fresh", "Fresh Start"), ("full", "Full Migration")],
                        default="fresh",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_migrations",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaction_migrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opening_migration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaction_migrations",
                        to="core.openingbalancemigration",
                    ),
                ),
            ],
            options={
                "db_table": "core_transaction_migration",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TransactionMigrationLine",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("pending_po", "Pending Purchase Order"),
                            ("pending_so", "Pending Sales Order"),
                            ("pending_grn", "Pending Goods Receipt Note"),
                            ("historical_journal", "Historical Journal Entry"),
                            ("historical_ap_invoice", "Historical AP Invoice"),
                            ("historical_ar_invoice", "Historical AR Invoice"),
                        ],
                        max_length=30,
                    ),
                ),
                ("row_number", models.IntegerField(default=0)),
                (
                    "raw_data",
                    models.JSONField(default=dict, help_text="Original CSV row data"),
                ),
                (
                    "data",
                    models.JSONField(
                        default=dict, help_text="Parsed and validated data"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("valid", "Valid"),
                            ("error", "Error"),
                            ("imported", "Imported"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("errors", models.JSONField(blank=True, default=list)),
                (
                    "migration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="core.transactionmigration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Migration Line",
                "db_table": "core_transaction_migration_line",
                "ordering": ["migration", "line_type", "row_number"],
            },
        ),
    ]
