# Generated by Django 6.0.5 on 2026-06-04 10:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_transactionmigration_transactionmigrationline"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="category",
            field=models.CharField(
                choices=[
                    ("crud", "CRUD"),
                    ("login", "Login"),
                    ("export", "Export"),
                    ("config", "Configuration"),
                    ("file", "File"),
                    ("approval", "Approval"),
                    ("bulk", "Bulk Operation"),
                ],
                db_index=True,
                default="crud",
                help_text="Audit category for grouping and filtering",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional context (export format, file name, etc.)",
            ),
        ),
        migrations.CreateModel(
            name="AuditExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        choices=[("csv", "CSV"), ("excel", "Excel")], max_length=10
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("record_count", models.PositiveIntegerField(default=0)),
                ("file_path", models.CharField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_exports",
                        to="core.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Export",
                "verbose_name_plural": "Audit Exports",
                "db_table": "core_audit_export",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLogBulk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("bulk_update", "Bulk Update"),
                            ("bulk_delete", "Bulk Delete"),
                            ("bulk_import", "Bulk Import"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("record_count", models.PositiveIntegerField(default=0)),
                (
                    "affected_models",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of model names affected",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_operations",
                        to="core.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log Bulk Operation",
                "verbose_name_plural": "Audit Log Bulk Operations",
                "db_table": "core_audit_log_bulk",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="auditlog",
            name="bulk_operation",
            field=models.ForeignKey(
                blank=True,
                help_text="Links individual audit entries to a parent bulk operation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="core.auditlogbulk",
            ),
        ),
        migrations.CreateModel(
            name="AuditRetention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("retention_years", models.PositiveIntegerField(default=7)),
                ("auto_archive", models.BooleanField(default=True)),
                ("last_archive_date", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_retention",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Retention Policy",
                "verbose_name_plural": "Audit Retention Policies",
                "db_table": "core_audit_retention",
            },
        ),
    ]
