# Generated by Django 6.0.5 on 2026-06-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_auditlog_category_auditlog_metadata_auditexport_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowdefinition",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("", "---------"),
                    ("financial.JournalEntry", "Journal Entry"),
                    ("scm.PurchaseOrder", "Purchase Order"),
                    ("scm.SalesOrder", "Sales Order"),
                    ("scm.GoodsReceiptNote", "Goods Receipt Note"),
                    ("scm.DeliveryOrder", "Delivery Order"),
                    ("crm.Quotation", "Quotation"),
                    ("crm.CustomerInvoice", "Customer Invoice"),
                    ("hrm.LeaveRequest", "Leave Request"),
                    ("hrm.Claim", "Claim"),
                    ("hrm.ExpenseReport", "Expense Report"),
                    ("mrp.WorkOrder", "Work Order"),
                    ("assets.AssetDisposal", "Asset Disposal"),
                    ("treasury.Payment", "Payment"),
                    ("treasury.Receipt", "Receipt"),
                ],
                max_length=100,
            ),
        ),
    ]
