# Generated by Django 6.0.5 on 2026-06-04 12:19

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0023_auditlog_category_auditlog_metadata_auditexport_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("equity", "Equity"),
                            ("revenue", "Revenue"),
                            ("expense", "Expense"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "subtype",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("current_asset", "Current Asset"),
                            ("non_current_asset", "Non-Current Asset"),
                            ("current_liability", "Current Liability"),
                            ("long_term_liability", "Long-Term Liability"),
                            ("equity", "Equity"),
                            ("revenue", "Revenue"),
                            ("cost_of_sales", "Cost of Sales"),
                            ("operating_expense", "Operating Expense"),
                            ("non_operating", "Non-Operating"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                ("level", models.PositiveIntegerField(default=0)),
                (
                    "is_group",
                    models.BooleanField(default=False, help_text="Has child accounts"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("mfrs_code", models.CharField(blank=True, default="", max_length=50)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="financial.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
                "db_table": "financial_account",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AccountCompany",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_assignments",
                        to="financial.account",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_assignments",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Company Assignment",
                "verbose_name_plural": "Account Company Assignments",
                "db_table": "financial_account_company",
                "unique_together": {("account", "company")},
            },
        ),
    ]
