# Generated by Django 6.0.5 on 2026-06-04 12:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_auditlog_category_auditlog_metadata_auditexport_and_more"),
        ("financial", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("entry_number", models.CharField(max_length=50, unique=True)),
                ("date", models.DateField(db_index=True)),
                ("description", models.TextField(blank=True, default="")),
                ("reference", models.CharField(blank=True, default="", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("posted", "Posted"),
                            ("reversed", "Reversed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "total_debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversal_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversals",
                        to="financial.journalentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal Entry",
                "verbose_name_plural": "Journal Entries",
                "db_table": "financial_journal_entry",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntryLine",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("line_number", models.PositiveIntegerField(default=0)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_lines",
                        to="financial.account",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="financial.journalentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal Entry Line",
                "verbose_name_plural": "Journal Entry Lines",
                "db_table": "financial_journal_entry_line",
                "ordering": ["line_number"],
            },
        ),
    ]
