# Generated by Django 6.0.5 on 2026-06-04 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_auditlog_category_auditlog_metadata_auditexport_and_more"),
        ("financial", "0002_journalentry_journalentryline"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gl_entries",
                        to="financial.account",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gl_entries",
                        to="core.company",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gl_entries",
                        to="financial.journalentry",
                    ),
                ),
                (
                    "journal_entry_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gl_entries",
                        to="financial.journalentryline",
                    ),
                ),
            ],
            options={
                "verbose_name": "General Ledger Entry",
                "verbose_name_plural": "General Ledger Entries",
                "db_table": "financial_general_ledger",
                "ordering": ["date", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["account", "date"],
                        name="financial_g_account_23b10b_idx",
                    ),
                    models.Index(
                        fields=["company", "date"],
                        name="financial_g_company_8f4890_idx",
                    ),
                ],
            },
        ),
    ]
