# Generated by Django 6.0.5 on 2026-06-04 13:40

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financial", "0003_generalledger"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxCode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "rate_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_type",
                    models.CharField(
                        choices=[
                            ("sales", "Sales Tax"),
                            ("service", "Service Tax"),
                            ("exempt", "Exempt"),
                            ("zero_rated", "Zero-Rated"),
                            ("out_of_scope", "Out of Scope"),
                            ("purchase", "Purchase / Input Tax"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Tax Code",
                "verbose_name_plural": "Tax Codes",
                "db_table": "financial_tax_code",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("rate_percent", models.DecimalField(decimal_places=2, max_digits=5)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
                (
                    "tax_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="financial.taxcode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tax Rate",
                "verbose_name_plural": "Tax Rates",
                "db_table": "financial_tax_rate",
                "ordering": ["-effective_from"],
            },
        ),
    ]
