# Generated by Django 6.0.5 on 2026-06-05 17:52

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_auditlog_category_auditlog_metadata_auditexport_and_more"),
        ("financial", "0004_taxcode_taxrate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("posted", "Posted"),
                    ("reversed", "Reversed"),
                ],
                db_index=True,
                default="draft",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="FinancialPeriod",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_open", models.BooleanField(default=True)),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False, help_text="Year-end close — no further postings"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_periods",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Period",
                "verbose_name_plural": "Financial Periods",
                "db_table": "financial_period",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="generalledger",
            name="period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="gl_entries",
                to="financial.financialperiod",
            ),
        ),
        migrations.AddIndex(
            model_name="generalledger",
            index=models.Index(
                fields=["period"], name="financial_g_period__13f7f3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="financialperiod",
            unique_together={("company", "start_date", "end_date")},
        ),
    ]
