# Generated by Django 6.0.5 on 2026-06-05 21:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_auditlog_category_auditlog_metadata_auditexport_and_more"),
        ("financial", "0005_period_and_status_updates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="financialperiod",
            options={
                "ordering": ["start_date"],
                "verbose_name": "Financial Period",
                "verbose_name_plural": "Financial Periods",
            },
        ),
        migrations.CreateModel(
            name="FinancialYear",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False,
                        help_text="Year-end close completed — no further postings",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_years",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Year",
                "verbose_name_plural": "Financial Years",
                "db_table": "financial_year",
                "ordering": ["-start_date"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.AddField(
            model_name="financialperiod",
            name="financial_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periods",
                to="financial.financialyear",
            ),
        ),
    ]
