# Generated by Django 6.0.5 on 2026-06-05 23:39

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_auditlog_category_auditlog_metadata_auditexport_and_more"),
        ("financial", "0006_financial_year_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportDefinition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("module", models.CharField(max_length=50)),
                ("category", models.CharField(blank=True, default="", max_length=50)),
                ("company_scoped", models.BooleanField(default=True)),
                (
                    "compute_type",
                    models.CharField(
                        choices=[("sql", "SQL"), ("python", "Python Service")],
                        max_length=20,
                    ),
                ),
                ("sql_template", models.TextField(blank=True)),
                (
                    "service_method",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("pre_aggregated", models.BooleanField(default=False)),
                ("supports_drill_down", models.BooleanField(default=False)),
                (
                    "group_field",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("show_subtotals", models.BooleanField(default=True)),
                ("show_grand_total", models.BooleanField(default=True)),
                ("page_size", models.PositiveIntegerField(default=100)),
                ("cache_ttl_seconds", models.PositiveIntegerField(default=300)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Report Definition",
                "verbose_name_plural": "Report Definitions",
                "db_table": "financial_report_definition",
            },
        ),
        migrations.CreateModel(
            name="ReportExport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "format",
                    models.CharField(
                        choices=[("csv", "CSV"), ("pdf", "PDF"), ("xlsx", "Excel")],
                        max_length=10,
                    ),
                ),
                ("params", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Generating"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="generating",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, upload_to="report_exports/%Y/%m/"),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_exports",
                        to="core.company",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="financial.reportdefinition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Export",
                "verbose_name_plural": "Report Exports",
                "db_table": "financial_report_export",
            },
        ),
        migrations.CreateModel(
            name="AccountPeriodBalance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "opening_debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "opening_credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "period_debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "period_credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "closing_debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "closing_credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_balances",
                        to="financial.account",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_balances",
                        to="core.company",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_balances",
                        to="financial.financialperiod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Period Balance",
                "verbose_name_plural": "Account Period Balances",
                "db_table": "financial_accountperiodbalance",
                "unique_together": {("account", "company", "period")},
            },
        ),
        migrations.CreateModel(
            name="ReportParameter",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("key", models.SlugField()),
                ("label", models.CharField(max_length=200)),
                (
                    "param_type",
                    models.CharField(
                        choices=[
                            ("period", "Period (single)"),
                            ("period_range", "Period Range"),
                            ("account_tree", "Account Tree (hierarchical)"),
                            ("account_multi", "Account Multi-Select"),
                            ("customer_multi", "Customer Multi-Select"),
                            ("vendor_multi", "Vendor Multi-Select"),
                            ("date", "Date"),
                            ("date_range", "Date Range"),
                            ("checkbox", "Checkbox"),
                            ("select", "Dropdown Select"),
                            ("text", "Text Input"),
                        ],
                        max_length=30,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("default_value", models.JSONField(blank=True, null=True)),
                (
                    "options_source",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("validation", models.JSONField(blank=True, default=dict)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="financial.reportdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Parameter",
                "verbose_name_plural": "Report Parameters",
                "db_table": "financial_report_parameter",
                "ordering": ["sort_order"],
                "unique_together": {("report", "key")},
            },
        ),
    ]
