# Generated by Django 6.0.5 on 2026-06-05 23:40
"""Data migration: backfill AccountPeriodBalance from existing GL entries."""

from django.db import migrations


def backfill_balances(apps, schema_editor):
    GeneralLedger = apps.get_model("financial", "GeneralLedger")
    AccountPeriodBalance = apps.get_model("financial", "AccountPeriodBalance")
    from django.db.models import Sum

    gl_entries = GeneralLedger.objects.values(
        "account_id", "company_id", "period_id"
    ).annotate(total_debit=Sum("debit"), total_credit=Sum("credit"))

    objs = []
    for entry in gl_entries:
        objs.append(
            AccountPeriodBalance(
                account_id=entry["account_id"],
                company_id=entry["company_id"],
                period_id=entry["period_id"],
                period_debit=entry["total_debit"],
                period_credit=entry["total_credit"],
                closing_debit=entry["total_debit"],
                closing_credit=entry["total_credit"],
            )
        )
    AccountPeriodBalance.objects.bulk_create(objs, ignore_conflicts=True)


def reverse_backfill(apps, schema_editor):
    AccountPeriodBalance = apps.get_model("financial", "AccountPeriodBalance")
    AccountPeriodBalance.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            "financial",
            "0007_reportdefinition_reportexport_accountperiodbalance_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(backfill_balances, reverse_backfill),
    ]
